using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace leet.LeetCode.Problems.FindTheDifference
{
    /*
     * Find the Difference
     * 
     * You are given two strings s and t.
     * 
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * 
     * Return the letter that was added to t.
     * 
     * https://leetcode.com/problems/find-the-difference/
     */
    public class Solution
    {
        public char FindTheDifference(string s, string t)
        {
            var dict = new Dictionary<char, int>() { };

            for (var i = 0; i < s.Length; i++)
            {
                if (dict.ContainsKey(s[i]))
                {
                    dict[s[i]]++;
                }
                else
                {
                    dict.Add(s[i], 1);
                }
            }

            for (var i = 0; i < t.Length; i++)
            {
                if (dict.ContainsKey(t[i]))
                {
                    dict[t[i]]--;

                    if (dict[t[i]] < 0)
                    {
                        return t[i];
                    }
                }
                else
                {
                    return t[i];
                }
            }

            throw new Exception("No letter was found added to string 't'. ");
        }
    }
}
